"""Filesystem helpers for Groundhog projects.

All project state lives on disk under ``projects/<name>/`` so that the
coding agent (which edits these files directly) and the Reflex app always
agree on the source of truth.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent.parent
PROJECTS_DIR = ROOT / "projects"
SETTINGS_FILE = ROOT / "settings.json"
PROMPTS_DIR = ROOT / "prompts"

# Prompt files carry a human-facing header, then "---", then the text sent
# to the agent.
PROMPT_HEADER_SEPARATOR = "\n---\n"

# Prefixed to an ANALYSIS.md the user wrote themselves, so the provenance is
# visible both to whoever reads the file and to the agent.
USER_ANALYSIS_NOTE = (
    "_Analysis written by the user rather than generated by an agent._"
)

RESULTS_HEADER = (
    "# Results\n\n"
    "| Experiment | Date | Metric | Value | Notes |\n"
    "| --- | --- | --- | --- | --- |\n"
)

EVAL_METRICS = ["AUC", "RMSE", "MASE", "MAPE"]
SPLIT_MODES = ["percentage", "column", "cv_folds"]
LOWER_IS_BETTER = {"RMSE", "MASE", "MAPE"}


class InvalidProjectName(ValueError):
    """Raised for a project name that ``create_project`` could not have made.

    Project names arrive from the ``/project/[name]`` route, so they are raw
    user input on every read path, not just at creation time.
    """


def slugify(name: str) -> str:
    """Turn a user-supplied project name into a filesystem-safe slug."""
    return re.sub(r"[^a-zA-Z0-9_-]+", "-", name.strip()).strip("-").lower()


def validate_project_name(name: str) -> str:
    """Return ``name`` unchanged if it is a name this app could have created.

    ``slugify`` is idempotent, so a name that is already its own slug is one
    that came out of ``create_project``. Anything else — path separators,
    ``..``, spaces, an empty string — is rejected. The empty string needs its
    own check because it *is* its own slug, and ``PROJECTS_DIR / ""`` is
    ``PROJECTS_DIR`` itself.
    """
    if not name or not isinstance(name, str) or slugify(name) != name:
        raise InvalidProjectName(f"Invalid project name: {name!r}")
    return name


def is_valid_project_name(name: str) -> bool:
    """Non-raising form of :func:`validate_project_name`, for UI guards."""
    try:
        validate_project_name(name)
    except InvalidProjectName:
        return False
    return True


def project_dir(name: str) -> Path:
    """The directory for ``name``, or raise if it is not a legitimate project.

    Every other path helper funnels through here, so this is the single point
    at which a name from the URL becomes a filesystem path.
    """
    path = PROJECTS_DIR / validate_project_name(name)
    # A valid slug can still escape via a symlink planted inside projects/,
    # which the name check alone cannot see.
    if not path.resolve().is_relative_to(PROJECTS_DIR.resolve()):
        raise InvalidProjectName(
            f"Project path escapes the projects directory: {name!r}"
        )
    return path


def data_dir(name: str) -> Path:
    return project_dir(name) / "data"


def experiments_dir(name: str) -> Path:
    return project_dir(name) / "experiments"


def results_path(name: str) -> Path:
    return project_dir(name) / "RESULTS.md"


def analysis_path(name: str) -> Path:
    return project_dir(name) / "ANALYSIS.md"


def metadata_path(name: str) -> Path:
    return project_dir(name) / "metadata.json"


def project_exists(name: str) -> bool:
    """Whether ``name`` is a usable project name with a directory on disk.

    An invalid name is reported as "does not exist" rather than raising, so
    callers that only care about presence (listings, existence checks) stay
    boolean. ``project_stage`` distinguishes invalid names as ``forbidden``.
    """
    try:
        return project_dir(name).is_dir()
    except InvalidProjectName:
        return False


def list_project_names() -> list[str]:
    """Every project directory the app is able to open.

    Directories created by hand with names the app could not have produced are
    skipped: every link and lookup on the home page passes the name back
    through ``project_dir``, so listing them would only produce dead links.
    """
    if not PROJECTS_DIR.is_dir():
        return []
    return sorted(
        p.name
        for p in PROJECTS_DIR.iterdir()
        if p.is_dir() and is_valid_project_name(p.name)
    )


def create_project(raw_name: str) -> str:
    """Create the on-disk skeleton for a new project and return its slug."""
    slug = slugify(raw_name)
    if not slug:
        raise ValueError(
            "Project name must contain at least one letter, number, - or _."
        )
    if project_exists(slug):
        raise ValueError(f"A project named '{slug}' already exists.")
    data_dir(slug).mkdir(parents=True, exist_ok=True)
    experiments_dir(slug).mkdir(parents=True, exist_ok=True)
    results_path(slug).write_text(RESULTS_HEADER)
    return slug


def safe_filename(filename: str, fallback: str = "dataset.csv") -> str:
    """Reduce an uploaded filename to a single, harmless path component.

    ``Path(...).name`` drops any directory part but keeps ``..`` intact, and
    returns an empty string for ``.`` — both of which would target the data
    directory itself rather than a file inside it.
    """
    candidate = Path(filename or "").name.strip()
    return fallback if candidate in {"", ".", ".."} else candidate


def list_data_files(name: str) -> list[str]:
    d = data_dir(name)
    if not d.is_dir():
        return []
    return sorted(p.name for p in d.iterdir() if p.is_file())


def save_data_file(name: str, filename: str, content: bytes) -> None:
    d = data_dir(name)
    d.mkdir(parents=True, exist_ok=True)
    (d / safe_filename(filename)).write_bytes(content)


def dataset_preview(name: str) -> dict:
    """Read the first dataset file and summarize row count + column stats."""
    files = list_data_files(name)
    if not files:
        return {"record_count": 0, "columns": []}
    path = data_dir(name) / files[0]
    df = pd.read_csv(path)
    columns = [
        {"name": col, "dtype": str(df[col].dtype), "n_unique": int(df[col].nunique())}
        for col in df.columns
    ]
    return {"record_count": len(df), "columns": columns}


def read_metadata(name: str) -> dict | None:
    path = metadata_path(name)
    if not path.is_file():
        return None
    return json.loads(path.read_text())


def write_metadata(name: str, metadata: dict) -> None:
    metadata_path(name).write_text(json.dumps(metadata, indent=2))


def parse_results(name: str) -> list[dict]:
    """Parse the experiment rows out of RESULTS.md's markdown table."""
    path = results_path(name)
    if not path.is_file():
        return []
    rows = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 5:
            continue
        if cells[0] in {"Experiment", ""} or set(cells[0]) == {"-"}:
            continue
        rows.append(
            {
                "experiment": cells[0],
                "date": cells[1],
                "metric": cells[2],
                "value": cells[3],
                "notes": cells[4],
            }
        )
    return rows


def top_result(name: str, eval_metric: str | None, rows: list[dict] | None = None) -> str:
    """Format the best metric value achieved so far, e.g. '0.91 (AUC)'."""
    rows = rows if rows is not None else parse_results(name)
    scored = []
    for row in rows:
        try:
            scored.append((float(row["value"]), row.get("metric") or eval_metric or ""))
        except (KeyError, ValueError):
            continue
    if not scored:
        return "—"
    metric = eval_metric or scored[0][1]
    values = [v for v, _ in scored]
    best = min(values) if metric in LOWER_IS_BETTER else max(values)
    return f"{best:g} ({metric})" if metric else f"{best:g}"


def list_experiments(name: str) -> list[str]:
    d = experiments_dir(name)
    if not d.is_dir():
        return []
    return sorted(p.name for p in d.iterdir() if p.is_dir())


def project_stage(name: str) -> str:
    """Which step of the setup flow a project is at, decided from disk alone.

    Invalid names (path traversal, empty, anything ``create_project`` could
    not have produced) are ``forbidden``, distinct from a well-formed slug
    that simply has no directory yet (``not_found``).
    """
    try:
        exists = project_dir(name).is_dir()
    except InvalidProjectName:
        return "forbidden"
    if not exists:
        return "not_found"
    if not list_data_files(name):
        return "upload"
    if read_metadata(name) is None:
        return "configure"
    if not has_analysis(name):
        return "analysis"
    return "summary"


def has_analysis(name: str) -> bool:
    """Whether the analysis run has produced an ANALYSIS.md for this project."""
    path = analysis_path(name)
    return path.is_file() and bool(path.read_text().strip())


def read_analysis(name: str) -> str:
    path = analysis_path(name)
    return path.read_text() if path.is_file() else ""


def write_analysis(name: str, text: str) -> None:
    """Store a user-written analysis, skipping the agent run.

    Raises ValueError on empty text, since an empty ANALYSIS.md would leave the
    project stuck at the analysis stage.
    """
    body = text.strip()
    if not body:
        raise ValueError("Analysis cannot be empty.")
    analysis_path(name).write_text(f"{USER_ANALYSIS_NOTE}\n\n{body}\n")


def has_experiments(name: str) -> bool:
    """Whether any experiment has been run, from either the directories or the
    results table. Used to avoid gating projects that predate the analysis
    stage."""
    return bool(list_experiments(name)) or bool(parse_results(name))


def read_prompt(kind: str) -> str:
    """Return the agent-facing body of ``prompts/<kind>.md``.

    Everything before the first ``---`` line is a header for humans reading the
    file and is stripped out. Returns an empty string if the file is missing so
    the caller can refuse to launch an agent with no instructions.
    """
    path = PROMPTS_DIR / f"{kind}.md"
    if not path.is_file():
        return ""
    text = path.read_text()
    _, separator, body = text.partition(PROMPT_HEADER_SEPARATOR)
    return (body if separator else text).strip()


def _write_json(path: Path, payload: dict) -> None:
    """Write JSON via a temp file + rename so a crash can't leave a torn file."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, indent=2))
    os.replace(tmp, path)


def read_settings() -> dict:
    """Read app settings, returning an empty dict if absent or unreadable."""
    if not SETTINGS_FILE.is_file():
        return {}
    try:
        return json.loads(SETTINGS_FILE.read_text())
    except (json.JSONDecodeError, OSError):
        return {}


def write_settings(settings: dict) -> None:
    _write_json(SETTINGS_FILE, settings)
